export default {
  '01a85c17': [() => import(/* webpackChunkName: '01a85c17' */ "@theme/BlogTagsListPage"), "@theme/BlogTagsListPage", require.resolveWeak("@theme/BlogTagsListPage")],
  '0e384e19': [() => import(/* webpackChunkName: '0e384e19' */ "@site/docs/intro.md"), "@site/docs/intro.md", require.resolveWeak("@site/docs/intro.md")],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ "@theme/DocPage"), "@theme/DocPage", require.resolveWeak("@theme/DocPage")],
  '1cc1aa5b': [() => import(/* webpackChunkName: '1cc1aa5b' */ "~blog/blog-tags-shopify-491.json"), "~blog/blog-tags-shopify-491.json", require.resolveWeak("~blog/blog-tags-shopify-491.json")],
  '20ac7829': [() => import(/* webpackChunkName: '20ac7829' */ "~docs/docs-route-ff2.json"), "~docs/docs-route-ff2.json", require.resolveWeak("~docs/docs-route-ff2.json")],
  '6875c492': [() => import(/* webpackChunkName: '6875c492' */ "@theme/BlogTagsPostsPage"), "@theme/BlogTagsPostsPage", require.resolveWeak("@theme/BlogTagsPostsPage")],
  '8be5b89e': [() => import(/* webpackChunkName: '8be5b89e' */ "~blog/blog-tags-tags-4c2.json"), "~blog/blog-tags-tags-4c2.json", require.resolveWeak("~blog/blog-tags-tags-4c2.json")],
  '8cf15a28': [() => import(/* webpackChunkName: '8cf15a28' */ "@site/blog/2020-06-29-welcome.md"), "@site/blog/2020-06-29-welcome.md", require.resolveWeak("@site/blog/2020-06-29-welcome.md")],
  'a6aa9e1f': [() => import(/* webpackChunkName: 'a6aa9e1f' */ "@theme/BlogListPage"), "@theme/BlogListPage", require.resolveWeak("@theme/BlogListPage")],
  'bbb4ffb5': [() => import(/* webpackChunkName: 'bbb4ffb5' */ "~blog/blog-c06.json"), "~blog/blog-c06.json", require.resolveWeak("~blog/blog-c06.json")],
  'c4f5d8e4': [() => import(/* webpackChunkName: 'c4f5d8e4' */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  'ccc49370': [() => import(/* webpackChunkName: 'ccc49370' */ "@theme/BlogPostPage"), "@theme/BlogPostPage", require.resolveWeak("@theme/BlogPostPage")],
  'd901fa1c': [() => import(/* webpackChunkName: 'd901fa1c' */ "~blog/blog-tags-introductions-7e3.json"), "~blog/blog-tags-introductions-7e3.json", require.resolveWeak("~blog/blog-tags-introductions-7e3.json")],
  'f491aeb1': [() => import(/* webpackChunkName: 'f491aeb1' */ "@site/blog/2020-06-29-welcome.md?truncated=true"), "@site/blog/2020-06-29-welcome.md?truncated=true", require.resolveWeak("@site/blog/2020-06-29-welcome.md?truncated=true")],};
